# Generated by Django 5.2.4 on 2025-08-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_tableheader_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'customer_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_name', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'customer_quotation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerQuotationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_date', models.DateField(blank=True, null=True)),
                ('quotation_address', models.TextField(blank=True, null=True)),
                ('quotation_subject', models.TextField(blank=True, null=True)),
                ('quotation_description', models.CharField(blank=True, max_length=255, null=True)),
                ('quotation_referrence', models.TextField(blank=True, max_length=255, null=True)),
                ('quotation_note', models.TextField(blank=True, null=True)),
                ('quotation_bank_details', models.TextField(blank=True, null=True)),
                ('quotation_signature', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'customer_quotation_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationTableHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'quotation_table_header',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationTableInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'quotation_table_instance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationTableValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('field_value', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'quotation_table_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableHeaderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'table_header_type',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='tableheader',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='tabledata',
            name='header',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='TableData',
        ),
        migrations.DeleteModel(
            name='TableHeader',
        ),
    ]
